### ISSUE TITLE
Highlighting while searching is absent

### ISSUE THREAD

**Issue by gdinesh-software** [owozsh/amora#3]
Highlighting while searching anything with "/" seems to have no effect. It would be great if someone included that in this awesome theme! Thank You!

![Screenshot (1)](https://user-images.githubusercontent.com/76434436/116604394-ad4bcf00-a94b-11eb-8c74-7a1d47eabd05.png)

**Comment by owozsh** [comment]
Update it ;) it's working here. Glad that you liked it :)
