### ISSUE TITLE
dark background after installing with vimplug

### ISSUE THREAD

**Issue by gabrielebarola** [owozsh/Amora#9]
i simply followed the instruction and installed with vimplug on neovim but it seams like the theme defaults to focus mode or something similar

**Comment by owozsh** [comment]
Can you share your init.vim? It's working perfectly fine here, maybe your bg is transparent or something similar.

**Comment by gabrielebarola** [comment]
my also tested with empty init.vim just with the vimplug command  to install the theme but same issue, if no one else is experiencing the same i can close the issue and try to find a solution for myself. thank you
